export const ROUTES = {
  ROOT: "/",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  PROFILE: "/profile",
  IDENTITY_USERS: "/identity/users",
  IDENTITY_USER_DETAIL: "/identity/users/:userId",
  AUTHORIZATION_ROLES: "/authorization/roles",
  AUTHORIZATION_ROLE_DETAIL: "/authorization/roles/:roleId",
  AUTHORIZATION_PERMISSIONS: "/authorization/permissions",
  AUTHORIZATION_PERMISSION_DETAIL: "/authorization/permissions/:permissionId",
  CONTENT_NEWS: "/content/news",
  CONTENT_NEWS_DETAIL: "/content/news/:articleId",
  CONTENT_CATEGORIES: "/content/categories",
  CONTENT_CATEGORY_DETAIL: "/content/categories/:categoryId",
  CONTENT_TAGS: "/content/tags",
  CONTENT_TAG_DETAIL: "/content/tags/:tagId",
  SEO: "/seo",
  SEO_METADATA: "/seo/metadata",
  SEO_METADATA_DETAIL: "/seo/metadata/:seoId",
  SEO_SLUG_ROUTES: "/seo/slug-routes",
  SEO_SLUG_ROUTE_DETAIL: "/seo/slug-routes/:slugId",
  SEO_ARTICLE_SETTINGS: "/seo/articles/:articlePublicId",
} as const;
